import { useRouter } from 'next/router';
import Head from 'next/head';
import { findCandidateByStackAndId } from '@/data/candidates';
import styles from '@/styles/Candidate.module.css';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faFileArrowDown, faTrash, faPhone } from '@fortawesome/free-solid-svg-icons';
import { fileIcons, getFileIconColor, faFile } from '@/utils/fileIcons';
import { statusValues } from '@/utils/constants';
import Layout from '@/components/Layout/Layout';
import Loading from '@/components/Loading/Loading';

const CandidateDetails = () => {
  const router = useRouter();
  const { stack, id } = router.query;
  const candidate = findCandidateByStackAndId(stack, id);

  if (!candidate) {
    return <Loading />;
  }

  return (
    <>
      <Head>
        <title>Codifin - {candidate.name}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout
        title="Candidate information"
        description="Select the information you want to see"
        buttonTxt="Contact"
        icon={<FontAwesomeIcon icon={faPhone} className={styles.icon_btn} />}
      >
        <div className={styles.main}>
          <div className={`${styles.candidate} ${styles.gradient}`}>
            <img src={candidate.profile} className={styles.pic} />
            <h3 className={styles.candidate_name}>{candidate.name}</h3>
            <p className={styles.candidate_stack}>{candidate.stack} Developer</p>
            <div className={styles.status}>
              <select id="statusSelect" className={styles.select} defaultValue={candidate.status}>
                {statusValues.map((status) => (
                  <option value={status.value} key={status.value}>
                    {status.label}
                  </option>
                ))}
              </select>
            </div>
          </div>
          <div className={styles.documents}>
            <h3 className={styles.title}>Recent files</h3>

            <div className={styles.files}>
              {candidate.files.map((file) => (
                <div className={styles.file}>
                  <div className={styles.file_title}>
                    <FontAwesomeIcon
                      icon={fileIcons[file.name.split('.').pop().toLowerCase()] || faFile}
                      className={styles.icon}
                      style={getFileIconColor(file.name)}
                    />
                    <p className={styles.file_name}>{file.name}</p>
                  </div>
                  <p className={styles.file_createdAt}>{file.createdAt}</p>
                  <FontAwesomeIcon icon={faFileArrowDown} className={`${styles.icon} ${styles.icon_download}`} />
                  <FontAwesomeIcon icon={faTrash} className={`${styles.icon} ${styles.icon_delete}`} />
                </div>
              ))}
            </div>
          </div>
        </div>
      </Layout>
    </>
  );
};

export default CandidateDetails;
