import React from 'react'
import Head from 'next/head'
import styles from '@/styles/StackPage.module.css'
import { stacks } from '../../data/stacks';
import Layout from '../../components/Layout/Layout';
import Link from 'next/link';
import { candidates } from '../../data/candidates';


/**
 Returns the stacks list
 localhost:3000/candidates
 */

const StackPage = () => {

  return (
    <>
    <Head>
      <title>Candidates Stack | Codifin</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Layout 
      title="Candidates Stack"
      description="Select the technology stack you want to see"
      buttonTxt="Add Stack"
      >
      <div className={styles.stack}>
          {
            stacks.map((stack, index) => (
              <Link href={`/candidates/${stack.name}`}>
              <div className={styles.stack_item} key={stack.id}>
                <div className={styles.stack_new}>+9</div>
                <div className={styles.stack_text}>
                  <h3 className={styles.stack_name}>{stack.name}</h3>
                </div>
                <div className={styles.stack_info}>
                   <img src={stack.icon} alt={stack.name} className={styles.stack_icon} />
                </div>
              </div>
            </Link>
            ))
                
          }
        </div> 
    </Layout>
  </>
  )
}

export default StackPage

