import { useRouter } from 'next/router';
import { candidates } from '@/data/candidates';
import styles from '@/styles/Stack.module.css'
import Head from 'next/head';
import Layout from '../../components/Layout/Layout';



const CandidateWorkforcePage = () => {
  const router = useRouter();
  const { id } = router.query;
  const filteredCandidates = candidates.filter(candidate => candidate.id === id);
  console.log("filteredCandidates")
  
  return (
    <>
     <Head>
      <title> Workforce| Codifin</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Layout
      title="Workforce - Candidate"
      description="Select the information you want to see"
      >
       
            <div className={styles.candidates}>
              
              
            </div>
        
    </Layout> 
    </>
  );
};

export default CandidateWorkforcePage;
