import React from 'react'
import Head from 'next/head';
import Link from 'next/link';
import Layout from '../../components/Layout/Layout';
import { candidates } from '@/data/candidates';
import styles from '@/styles/Stack.module.css'

const WorkforcePage = () => {
  return (
    <>
        <Head>
            <title>Codifin - Workforce </title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Layout
            title="Workforce"
            description="Select the hire candidate you want to see"
        >
            <div className="main">
            <div className={styles.candidates}>
                {
                  candidates.map((candidate, index) => (
                    candidate.status === "Hired" && (
                      <Link href={`/workforce/${candidate.id}`}>
                        <div className={styles.candidate} key={candidate.id}>
                          <img src={candidate.profile} className={styles.profile_pic} />
                          <h3 className={styles.candidate_name}>{candidate.name}</h3>
                        </div>
                      </Link>

                    )
                  ))
                }
             </div>

            </div>
        </Layout>
    </>
  )
}

export default WorkforcePage