import React from 'react'
import Head from 'next/head';
import Layout from '../../components/Layout/Layout';

const index = () => {
  return (
    <>
        <Head>
            <title>Codifin - Analysis </title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Layout
            title="Analysis"
            description="Select the information you want to see"
        >
            <div className="main">
                
            </div>
        </Layout>
    </>
  )
}

export default index